apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  type: NodePort
  selector:
    app: python-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
